server:
  port: 8305

spring:
  application:
    name: kafka-consumer
  main:
    allow-bean-definition-overriding: true
  datasource:
    bank:
      username: ${db_user_name}
      password: ${db_user_pwd}
      url: jdbc:mysql://${db_ip}/bankb?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
