server:
  port: 8324
dtm:
  invoke:
    mode: ${invoke_mode}
spring:
  application:
    name: dtm-mq-consumer
  main:
    allow-bean-definition-overriding: true
  datasource:
    bank:
      username: ${db_user_name}
      password: ${db_user_pwd}
      url: jdbc:mysql://${db_ip}/bankb?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka_ip}:8761/eureka/
  instance:
    prefer-ip-address: true
