port: 1117
APPLICATION_ID: dtm
service_description:
  name: dtm-kafka-consumer
  version: 1.0.1
  environment: development
servicecomb:
  request: #请求配置
    timeout: 60000 #微服务消费端超时时间,60s
  metrics:
    enabled: false
  monitor:
    client:
      enable: false
  release_way: canary  #新版本灰度开关
  service:
    registry:
      address: ${cse_address}
      instance:
        watch: false
        pull:
          interval: 1
  rest:
    address: 0.0.0.0:${port} #"[::]:1111?sslEnabled=false"
  handler:
    chain:
      Consumer:
        default: loadbalance,bizkeeper-consumer,dtm-consumer
      Provider:
        default: dtm-provider
spring:
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrapServers: ${bootstrap_servers}  
  datasource:
    bank:
      username: ${db_user_name}
      password: ${db_user_pwd}
      url: jdbc:mysql://${db_ip}:3306/bankb?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
