server:
  port: 8104

dtm:
  invoke:
    mode: feign
spring:
  application:
    name: dtm-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
