server:
  port: 8323
dtm:
  invoke:
    mode: ${invoke_mode}
spring:
  application:
    name: dtm-mq
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka_ip}:8761/eureka/
  instance:
    prefer-ip-address: true
