server:
  port: 8106
dtm:
  invoke:
    mode: ${invoke_mode}
spring:
  application:
    name: dtm-kafka
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrapServers: ${bootstrap_servers}  
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka_ip}:8761/eureka/
  instance:
    prefer-ip-address: true
